[project]
name = "cli-entry"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.12.0",
    "pytest>=9.0.2",
    "ruff>=0.14.11",
]
